package clinic.model;

/**
 * Stores the basic information for one clinic patient.
 *
 * The patient ID is generated by DataStore and is used by the appointment
 * screens to connect patients with their appointments.
 */
public class Patient {
    private int id;
    private String name;
    private int age;
    private String contact;

    /**
     * Creates a patient record with the ID and details entered in the GUI.
     */
    public Patient(int id, String name, int age, String contact) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.contact = contact;
    }

    /**
     * Returns the unique patient ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Updates the patient ID.
     *
     * This is rarely needed in the app, but it keeps the model flexible for
     * future integration work.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the patient's full name.
     */
    public String getName() {
        return name;
    }

    /**
     * Updates the patient's full name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the patient's age.
     */
    public int getAge() {
        return age;
    }

    /**
     * Updates the patient's age.
     */
    public void setAge(int age) {
        this.age = age;
    }

    /**
     * Returns the contact number or contact text entered for the patient.
     */
    public String getContact() {
        return contact;
    }

    /**
     * Updates the patient's contact information.
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * Shows a short patient label in lists and debugging messages.
     */
    @Override
    public String toString() {
        return "ID: " + id + " | " + name;
    }
}
